name: ghcr-oci-chart-releaser

description: Creates a release of the chart on push to main

inputs:
  chart-name:
    description: The name of the chart to release
    required: true

runs:
  using: composite
  steps:
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          VERSION=$(helm show chart ./charts/${{ inputs.chart-name }} | grep '^version:' | cut -d ' ' -f 2)
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Publish Helm chart to GHCR
        run: |
          helm package charts/${{ inputs.chart-name }}
          helm push ${{ inputs.chart-name }}-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/defenseunicorns/helm-charts
          rm ${{ inputs.chart-name }}-${{ steps.prep.outputs.VERSION }}.tgz