name: release

on:
  push:

defaults:
  run:
    shell: bash -e -x -o pipefail {0}

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  get-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-charts.outputs.charts }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get chart names
        id: set-charts
        run: |
          chart_list=$(ls -d ./charts/*/ | awk -F'/' '{printf "\"%s\", ", $3}')
          chart_list="[${chart_list%, }]"
          echo "Charts: $chart_list"
          echo "charts=$chart_list" >> "$GITHUB_OUTPUT"

  debug-job:
    runs-on: ubuntu-latest
    needs: get-charts
    steps:
      - env:
          CHARTS: ${{ needs.get-charts.outputs.charts }}
        run: |
          echo "Charts: $CHARTS"

  release:
    needs: get-charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart-name: ${{ needs.get-charts.outputs.charts }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: debug
        run: |
          echo "Chart name: ${{ matrix.chart-name }}"


      - name: chart-release
        uses: ./.github/actions/chart-release
        with:
          chart-name: ${{ matrix.chart-name }}
