name: release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -e -o pipefail {0}

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  get-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-charts.outputs.charts }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get chart names
        id: set-charts
        run: |
          chart_list=$(ls -d ./charts/*/ | awk -F'/' '{printf "\"%s\", ", $3}')
          chart_list="[${chart_list%, }]"
          echo "Charts: $chart_list"
          echo "charts=$chart_list" >> "$GITHUB_OUTPUT"

  release:
    needs: get-charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart-name: ${{ fromJson(needs.get-charts.outputs.charts) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'charts/${{ matrix.chart-name }}/**/*.{yml,yaml,tpl}'

      - name: chart-release
        if: steps.changes.outputs.src == 'true'
        uses: ./.github/actions/chart-release
        with:
          chart-name: ${{ matrix.chart-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
