#shamelessly stolen from https://github.com/stefanprodan/podinfo/blob/master/.github/workflows/release.yml
name: release

on:
  push:
    branches: main

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  login:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Publish Helm chart to GHCR
        run: |
          helm package charts/raw
          helm push defenseunicorns-raw-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/defenseunicorns/helm-charts
          rm defenseunicorns-raw-${{ steps.prep.outputs.VERSION }}.tgz